  
theme: jekyll-theme-minimal
title: <a href="https://hendejac.github.io/titanic_ml/">Titanic Machine Learning</a>
description: > # your text below (remove <br> elements if you don't need line breaks)
 A short machine-learning example.
  <br>
  <br>
  <a href="https://hendejac.github.io/">Return to Portfolio</a>
  <br>
theme: jekyll-theme-minimal
